model:
  name: cnn
  input_shape: [1, 28, 28]  # [channels, height, width] - [1, 28, 28] for MNIST, [3, 32, 32] for CIFAR-10
  num_classes: 10
  filters: [16, 32, 64, 128]  # Numero di filtri per ciascun layer - [32, 64, 128, 256] per CIFAR-10 - per MNIST [16, 32, 64, 128]
  kernel_size: 3
  residual: false  # Se utilizzare connessioni residuali

training:
  learning_rate: 0.001
  batch_size: 128
  num_epochs: 50
  weight_decay: 0.0001
  checkpoint_dir: checkpoints/
  log_every: 10
  save_every: 5
  early_stopping_patience: 7
  optimizer: adam  # [adam, sgd]
  scheduler: reduce_lr  # [reduce_lr, cosine]

dataset:
  name: mnist  # [mnist, cifar10]
  data_dir: data/
  val_size: 5000  # Dimensione del set di validazione